server:
  port: 8092
spring:
  datasource:
    url: jdbc:h2:mem:hotel_service;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS hotel_service\;SET SCHEMA hotel_service
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: hotel_service
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: true
    default-schema: hotel_service
    change-log: classpath:/db.changelog/db.changelog-master.yaml